import Head from "next/head";
import Image from "next/image";
import logo from "../public/assets/logo.png";
import styles from "@/styles/Home.module.css";
import Counter from "@/components/Counter";
import HomeComponent from "@/components/Home";
import Headers from "@/components/Header";

export default function Home() {
  return (
    <div className="min-h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {
        //For the launch of the website, a countdown counter was created which is rendered if the date is before April 12, 2023 16:00:00
        // Otherwise the Home page (HomeComponent) is rendered
      }
      {new Date("April 12, 2023 16:00:00").getTime() >= new Date().getTime() ? (
        <Counter />
      ) : (
        <HomeComponent />
      )}
    </div>
  );
}
